[package]
name = "reify2"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.38.0"
cstr = "0.2.12"
gpu-allocator = "0.26.0"
pretty_env_logger = "0.5.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-tracy = "0.11.0"
winit = "0.30.0"
