[package]
name = "reify2"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.38.0"
bytemuck = { version = "1.16.0", features = ["derive"] }
gpu-allocator = "0.26.0"
tracing = "0.1.40"
tracing-log = "0.2.0"

[dev-dependencies]
pretty_env_logger = "0.5.0"
tracing-subscriber = "0.3.18"
tracing-tracy = "0.11.0"
winit = "0.30.0"
